[package]
name = "wnka_ubtm"
version = "0.0.2"
edition = "2021"

[[bin]]
name = "wnka_ubtm"
path = "src/main.rs"

[dependencies]
uefi = { version = "0.28", features = ["alloc"] }
uefi-macros = "0.13"
goblin = { version = "0.9", default-features = false, features = ["elf32", "elf64", "endian_fd", "alloc"] }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true